from typing import Dict, List, Optional

from langchain_core.messages import BaseMessage, HumanMessage

from models.risk_flags import RiskFlag
from models.role_intelligence_profile import RoleIntelligenceProfile


STAGE3_SYSTEM_PROMPT = """\
You are KnowledgeKeeper. You have now completed both the business interview (Stage 1) and the \
employee interview (Stage 2). You have a complete Role Intelligence Profile and a full interview \
transcript.

Your task is to synthesise everything into a structured, professional Handover Intelligence Document. \
This document should read as though it was written by a senior consultant who deeply understands \
the role — not as a transcript summary.

## DOCUMENT GENERATION RULES

- Write in clear, professional prose. Use headers and sub-sections for navigation. Use bullet \
points only for lists of items (contacts, tools, tasks) — never for narrative content.
- Never quote the employee verbatim unless the exact phrasing is critical. Paraphrase and synthesise.
- Write for the incoming replacement — assume they are competent but have no prior context about \
this specific business, role, or environment.
- Where the employee's answers revealed gaps, uncertainty, or partial information, flag it \
explicitly with [GAP: brief description of what is missing] rather than glossing over it.
- Any Risk Flags tracked during Stage 2 appear prominently in the Risk Summary at the top of \
the document.
- Calibrate the depth of each section to the knowledge priority ranking from Stage 1.
- Each section MUST begin with the exact sentinel marker format: ### SECTION: [Section Name]
- Do not use any other heading format for section delimiters.\
"""


GENERATION_INSTRUCTION_TEMPLATE = """\
## GENERATION INSTRUCTION

Produce the complete Handover Intelligence Document with ALL of the following sections, each \
beginning with the exact sentinel marker shown. Do not skip any section — if information is \
not available for a section, write a brief note explaining what was not covered and why.

Required sections (in this exact order):
1. ### SECTION: Document Header
2. ### SECTION: Risk Summary
3. ### SECTION: Role Overview
4. ### SECTION: Knowledge Transfer — {priority_1_label}
5. ### SECTION: Knowledge Transfer — {priority_2_label}
6. ### SECTION: Knowledge Transfer — {priority_3_label}
7. ### SECTION: Key Relationships
8. ### SECTION: Systems and Access
9. ### SECTION: In-Flight Items
10. ### SECTION: Decision-Making Logic and Judgment
11. ### SECTION: Undocumented Knowledge
12. ### SECTION: Advice to Your Replacement
13. ### SECTION: Recommended Onboarding Plan
14. ### SECTION: Knowledge Gaps and Recommended Follow-Up

{confidentiality_instruction}

Tone guidance: The company culture is described as "{culture_type}". Match the document's formality \
to this culture — use professional but accessible language for informal cultures, and more structured \
formal language for formal cultures.

After the final section, add this footer:
"This document has been generated by KnowledgeKeeper. It is based on {question_count} questions \
across two interview sessions. {risk_flag_count} risk flags were identified and are summarised \
in Section 2. This document is ready to share with {recipients}."
"""


def build_context_block(
    profile: RoleIntelligenceProfile,
    conversation_history: List[BaseMessage],
    risk_flags: List[RiskFlag],
    answers: Dict[str, str],
    block_order: List[str],
    block_depths: Dict[str, str],
) -> str:
    """Build the full context string passed to the LLM for document generation."""
    parts = []

    # 1. Role Intelligence Profile
    parts.append("## ROLE INTELLIGENCE PROFILE\n")
    parts.append(_format_profile_for_context(profile))

    # 2. Risk Flags
    if risk_flags:
        parts.append("\n## RISK FLAGS IDENTIFIED\n")
        parts.append(_format_risk_flags(risk_flags))

    # 3. Interview transcript by block
    parts.append("\n## INTERVIEW TRANSCRIPT BY BLOCK\n")
    parts.append(_format_answers_by_block(answers, block_order, block_depths))

    # 4. Key conversation exchanges
    excerpts = _format_conversation_excerpts(conversation_history)
    if excerpts:
        parts.append("\n## KEY CONVERSATION EXCHANGES\n")
        parts.append(excerpts)

    # 5. Generation instruction
    parts.append("\n")
    parts.append(_build_generation_instruction(profile, answers, risk_flags))

    return "\n".join(parts)


def _format_profile_for_context(profile: RoleIntelligenceProfile) -> str:
    """Serialise the full profile into readable text for the LLM."""
    data = profile.model_dump() if hasattr(profile, "model_dump") else profile

    tools = ", ".join(data.get("key_tools", [])) if data.get("key_tools") else "Not specified"
    recipients = ", ".join(data.get("recipients", [])) if data.get("recipients") else "Not specified"
    supporting = ", ".join(data.get("supporting_categories", [])) if data.get("supporting_categories") else "None"

    lines = [
        "### Business Context",
        f"- Company: {data.get('company_name') or 'Not specified'}",
        f"- Industry: {data.get('industry', 'Unknown')}",
        f"- Team Structure: {data.get('team_structure', 'Unknown')}",
        f"- Key Tools & Platforms: {tools}",
        f"- Culture Type: {data.get('culture_type', 'Unknown')}",
        f"- Previous Knowledge Loss: {data.get('previous_knowledge_loss') or 'None reported'}",
        "",
        "### Vacant Role",
        f"- Job Title: {data.get('job_title', 'Unknown')}",
        f"- Department: {data.get('department', 'Unknown')}",
        f"- Tenure: {data.get('tenure', 'Unknown')}",
        f"- Reports To: {data.get('reports_to', 'Unknown')}",
        f"- Direct Reports: {data.get('direct_reports') or 'None'}",
        f"- Role Type: {data.get('role_type', 'Unknown')}"
        f"{' (' + data['role_type_weighting'] + ')' if data.get('role_type_weighting') else ''}",
        f"- Immediate Risk if No Handover: {data.get('immediate_risk', 'Unknown')}",
        f"- Known Undocumented Areas: {data.get('undocumented_areas') or 'None identified'}",
        f"- Key External Relationships: {data.get('key_external_relationships') or 'None'}",
        f"- System Access / Credentials: {data.get('system_access_gaps') or 'None'}",
        "",
        "### Replacement Profile",
        f"- Hire Type: {data.get('hire_type', 'Unknown')}",
        f"- Experience Level: {data.get('replacement_experience_level', 'Unknown')}",
        f"- Most Important Context: {data.get('most_important_context', 'Unknown')}",
        f"- 90-Day Success Definition: {data.get('success_definition_90_days', 'Unknown')}",
        f"- Overlap Period: {data.get('overlap_period') or 'No overlap planned'}",
        "",
        "### Knowledge Priorities (ranked)",
        f"1. {data.get('priority_1', 'Unknown')}",
        f"2. {data.get('priority_2', 'Unknown')}",
        f"3. {data.get('priority_3', 'Unknown')}",
        f"Supporting: {supporting}",
        "",
        "### Output Preferences",
        f"- Document Destination: {data.get('document_destination', 'Unknown')}",
        f"- Recipients: {recipients}",
        f"- Confidential Sections: {data.get('confidential_sections') or 'None specified'}",
        "",
        "### Departure Context",
        f"- Departure Type: {data.get('departure_type', 'Unknown')}",
        f"- Leaving on Good Terms: {data.get('leaving_on_good_terms', 'Unknown')}",
        f"- Employee Aware: {data.get('employee_aware', 'Unknown')}",
        f"- Sensitivity Flags: {data.get('sensitivity_flags') or 'None'}",
        f"- Notice Period: {data.get('notice_period', 'Unknown')}",
    ]

    return "\n".join(lines)


def _format_risk_flags(risk_flags: List[RiskFlag]) -> str:
    """Group risk flags by severity and format each."""
    grouped: Dict[str, List[RiskFlag]] = {"critical": [], "high": [], "medium": []}
    for flag in risk_flags:
        severity = flag.severity.value if hasattr(flag.severity, "value") else str(flag.severity)
        grouped.setdefault(severity, []).append(flag)

    lines = []
    for severity in ["critical", "high", "medium"]:
        flags = grouped.get(severity, [])
        if not flags:
            continue
        label = {"critical": "CRITICAL", "high": "HIGH", "medium": "MEDIUM"}.get(severity, severity.upper())
        lines.append(f"### {label}")
        for flag in flags:
            flag_type = flag.flag_type.value if hasattr(flag.flag_type, "value") else str(flag.flag_type)
            lines.append(f"- [{flag_type}] {flag.description}")
            lines.append(f"  Recommended action: {flag.recommended_action}")
            lines.append(f"  Source: {flag.source_block} (question {flag.source_question_index})")
        lines.append("")

    return "\n".join(lines)


def _format_answers_by_block(
    answers: Dict[str, str],
    block_order: List[str],
    block_depths: Dict[str, str],
) -> str:
    """Group answers by block in priority order."""
    lines = []

    # Role orientation first
    orientation_answers = {k: v for k, v in answers.items() if k.startswith("role_orientation.")}
    if orientation_answers:
        lines.append("### Role Orientation")
        for key in sorted(orientation_answers.keys(), key=lambda k: int(k.split(".")[1])):
            index = key.split(".")[1]
            lines.append(f"Q{index}: {orientation_answers[key]}")
        lines.append("")

    # Knowledge blocks in priority order
    for block in block_order:
        block_answers = {k: v for k, v in answers.items() if k.startswith(f"{block}.")}
        if not block_answers:
            continue
        depth = block_depths.get(block, "full")
        label = block.replace("_", " ").title()
        lines.append(f"### {label} [{depth} depth]")
        for key in sorted(block_answers.keys(), key=lambda k: int(k.split(".")[1])):
            index = key.split(".")[1]
            lines.append(f"Q{index}: {block_answers[key]}")
        lines.append("")

    # Closing sequence
    closing_answers = {k: v for k, v in answers.items() if k.startswith("closing_sequence.")}
    if closing_answers:
        lines.append("### Closing Questions")
        for key in sorted(closing_answers.keys(), key=lambda k: int(k.split(".")[1])):
            index = key.split(".")[1]
            lines.append(f"Q{index}: {closing_answers[key]}")
        lines.append("")

    return "\n".join(lines)


def _format_conversation_excerpts(conversation_history: List[BaseMessage]) -> str:
    """Extract substantive human turns from the conversation history."""
    excerpts = []
    for msg in conversation_history:
        if isinstance(msg, HumanMessage) and len(msg.content) > 100:
            excerpts.append(msg.content)
            if len(excerpts) >= 30:
                break

    if not excerpts:
        return ""

    lines = []
    for i, excerpt in enumerate(excerpts, 1):
        lines.append(f"[{i}] {excerpt}")
    return "\n\n".join(lines)


def _build_generation_instruction(
    profile: RoleIntelligenceProfile,
    answers: Dict[str, str],
    risk_flags: List[RiskFlag],
) -> str:
    """Build the generation instruction with profile-specific values."""
    data = profile.model_dump() if hasattr(profile, "model_dump") else profile

    priority_1_label = str(data.get("priority_1", "Priority 1")).replace("_", " ").title()
    priority_2_label = str(data.get("priority_2", "Priority 2")).replace("_", " ").title()
    priority_3_label = str(data.get("priority_3", "Priority 3")).replace("_", " ").title()

    confidential = data.get("confidential_sections")
    if confidential:
        confidentiality_instruction = (
            f'CONFIDENTIALITY WARNING: The manager has flagged the following as confidential: '
            f'"{confidential}". Do NOT include confidential content in those sections — write '
            f'"[CONFIDENTIAL — content omitted per manager\'s instruction]" in place of any '
            f"sensitive material."
        )
    else:
        confidentiality_instruction = ""

    question_count = len(answers)
    risk_flag_count = len(risk_flags)
    recipients = ", ".join(data.get("recipients", [])) if data.get("recipients") else "the designated recipients"
    culture_type = str(data.get("culture_type", "mixed"))

    return GENERATION_INSTRUCTION_TEMPLATE.format(
        priority_1_label=priority_1_label,
        priority_2_label=priority_2_label,
        priority_3_label=priority_3_label,
        confidentiality_instruction=confidentiality_instruction,
        culture_type=culture_type,
        question_count=question_count,
        risk_flag_count=risk_flag_count,
        recipients=recipients,
    )
